spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  jackson:
    deserialization:
      fail-on-unknown-properties : true
    servlet:
      multipart:
        enabled: true
        max-file-size: 200MB
        max-request-size: 215MB
    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
file:
  upload-dir: ./file/UPLOAD_FILES



jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE