spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  jackson:
    deserialization:
      fail-on-unknown-properties : true
    servlet:
      multipart:
        enabled: true
        max-file-size: 200MB
        max-request-size: 215MB
    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  thumbnail-dir: ./files/thumbnailImg


jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

log:
  systemName: JukBang
  level: ERROR
  slack:
    enabled: true
    webHookUrl: https://hooks.slack.com/services/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
    channel: error-report-bot
    userName: "[API]ErrorReportBot"
  database:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE