= Jukbang REST API Guide
Always0ne;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-response-body-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다.
[[AuthError]]
=== Auth Error
[[E0001]]
==== Error0001
operation::0001[snippets='response-body']
[[E0002]]
==== Error0002
operation::0002[snippets='response-body']
[[E0003]]
==== Error0003
operation::0003[snippets='response-body']
[[E0004]]
==== Error0004
operation::0004[snippets='response-body']
[[E0005]]
==== Error0005
operation::0005[snippets='response-body']
[[E0006]]
==== Error0006
operation::0006[snippets='response-body']


[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[AuthApi]]
=== 인증 API
[[signin]]
==== 인증하기

operation::signin[snippets='http-request,response-body']

[[signup]]
==== 회원가입하기

operation::signup[snippets='http-request,response-body']

[[checkid]]
==== 아이디 중복 확인하기

operation::idcheck[snippets='http-request,response-body']

[[refreshToken]]
==== 토큰 재발급 받기

operation::refresh[snippets='http-request,response-body']

[[AdminApi]]
=== 관리자 API

[[suouldPermitRooms]]
==== 승인받아야 할 방 리스트 조회

operation::shouldPermitRooms[snippets='http-request,response-body']

[[permitRoom]]
==== 방 승인하기

operation::permitRoom[snippets='http-request,response-body']

[[rejectRoom]]
==== 방 거절하기

operation::rejectRoom[snippets='http-request,response-body']


[[Community]]
=== 커뮤니티 API

[[Post]]
==== 게시글 서비스

[[getPostList]]
===== 게시글 목록 조회하기

operation::getPostList[snippets='http-request,response-body']

[[getPost]]
===== 게시글 조회하기

operation::getPost[snippets='http-request,response-body']

[[createPost]]
===== 게시글 생성하기

operation::createPost[snippets='http-request,response-body']

[[updatePost]]
===== 게시글 수정하기

operation::updatePost[snippets='http-request,response-body']

[[deletePost]]
===== 게시글 삭제하기

operation::deletePost[snippets='http-request,response-body']

[[Comment]]
==== 댓글 서비스

[[createComment]]
===== 댓글 생성하기

operation::createComment[snippets='http-request,response-body']

[[getComment]]
===== 댓글 조회하기

operation::getCommentsList[snippets='http-request,response-body']

[[updateComment]]
===== 댓글 수정하기

operation::updateComment[snippets='http-request,response-body']

[[deleteComment]]
===== 댓글 삭제하기

operation::deleteComment[snippets='http-request,response-body']

[[ChatApi]]
=== 채팅 API

[[Chat]]
==== 채팅 서비스

[[createMessage]]
===== 채팅방 만들기

operation::createMessage[snippets='http-request,response-body']


[[sendMessage]]
===== 메시지 보내기

operation::sendMessage[snippets='http-request,response-body']

[[getMessageList]]
===== 메시지 불러오기

operation::getMessageList[snippets='http-request,response-body']

[[deleteMessage]]
===== 메시지 삭제하기

operation::deleteMessage[snippets='http-request,response-body']

[[RoomApi]]
=== 방 API

[[Room]]
==== 방 서비스

[[createRoom]]
===== 판매자 방 게시하기

operation::createSellerRoom[snippets='http-request,response-body']

[[deleteRoom]]
===== 판매자 방 삭제하기

operation::deleteRoom[snippets='http-request,response-body']

[[getRoomList]]
===== 방 리스트 가져오기

operation::getRoomList[snippets='http-request,response-body']

[[getRoomDetail]]
===== 방 상세정보 가져오기

operation::getRoomDetail[snippets='http-request,response-body']

[[getSellerRoomList]]
===== 판매자 방 리스트 가져오기

operation::getSellerRoomList[snippets='http-request,response-body']

[[updateRoom]]
===== 방 수정하기

operation::updateRoom[snippets='http-request,response-body']

[[Review]]
==== 리뷰 서비스

[[createReview]]
===== 리뷰 작성하기

operation::createReview[snippets='http-request,response-body']

[[deleteReview]]
===== 리뷰 삭제하기

operation::deleteReview[snippets='http-request,response-body']

[[getReviewList]]
===== 리뷰 리스트 가져오기

operation::getReviewList[snippets='http-request,response-body']

[[updateReview]]
===== 리뷰 수정하기

operation::updateReview[snippets='http-request,response-body']



[[UserApi]]
=== 사용자 API

[[Favorite]]
==== 찜 서비스

[[getFavoriteList]]
===== 사용자의 찜 목록 가져오기

operation::getFavoriteList[snippets='http-request,response-body']

[[crateFavorite]]
===== 방 찜하기

operation::createFavorite[snippets='http-request,response-body']

[[deleteFavorite]]
===== 찜 취소하기

operation::deleteFavorite[snippets='http-request,response-body']

[[Report]]
==== 신고 서비스

[[createReport]]
===== 신고하기

operation::createReport[snippets='http-request,response-body']

[[getReports]]
===== 신고 리스트 조회하기

operation::getReports[snippets='http-request,response-body']

[[getReport]]
===== 신고 조회하기

operation::getReport[snippets='http-request,response-body']

[[deleteReport]]
===== 신고 삭제하기

operation::deleteReport[snippets='http-request,response-body']

[[Profile]]
==== 프로필 서비스

[[getUser]]
===== 유저 정보 조회하기

operation::getUser[snippets='http-request,response-body']

[[updateUser]]
===== 유저 정보 수정하기

operation::updateUser[snippets='http-request,response-body']

[[deleteUser]]
===== 유저 삭제하기

operation::deleteUser[snippets='http-request,response-body']

[[getMyPosts]]
===== 내가 쓴 게시글들 보기

operation::getMyPosts[snippets='http-request,response-body']